### ISSUE TITLE
Demo renders incorretly in Firefox

### ISSUE THREAD

**Issue by simevidas** [Jimdo/range-slider-sass#5]
URL: http://jimdo.github.io/range-slider-sass/

The bar is missing in Firefox (on Windows 10).

![capture](https://cloud.githubusercontent.com/assets/716405/16127226/c60f48d4-33fb-11e6-9f93-3d42e4990cf7.PNG)

**Comment by lassediercks** [comment]
@simevidas thanks so much for the heads up. It should be fixed, can you check again?

**Comment by simevidas** [comment]
@lassediercks Works after hard refresh +1

**Comment by lassediercks** [comment]
awesome!
